steps:
  # Build the Container Image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/laook-api:${_VERSION}", "."]
  # Push the Container Image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/laook-api:${_VERSION}"]
  # Deploy the Container Image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "laook-api",
        "--image",
        "gcr.io/$PROJECT_ID/laook-api:${_VERSION}",
        "--region",
        "asia-southeast2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

substitutions:
  _VERSION: "1.0"
