name: Cloud Build and Deploy

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Replace with your desired Python version

      - name: Install Google Cloud SDK
        run: |
          curl https://sdk.cloud.google.com | bash
          exec -l $SHELL
          gcloud components update --quiet

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_AUTH_KEY }}'

      - name: Set up Google Cloud SDK
        run: |
          gcloud config set project ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: Build and Deploy
        run: |
          gcloud builds submit --config=cloudbuild.yaml --substitutions=_VERSION=$VERSION .
        env:
          VERSION: ${{ github.sha }}
